=== snowfrs/clusterscheduler/source/dist/util/resources/json-schemas/definition-file.schema.json
{
   "$schema": "https://json-schema.org/draft/2020-12/schema",
   "$id": "https://github.com/hpc-gridware/clusterscheduler/tree/master/source/dist/util/resources/json-schemas/definition-file.schema.json",
   "type": "object",
   "required": [
      "className",
      "summary",
      "description",
      "cullPrefix",
      "attributes"
   ],
   "properties": {
      "className": {
         "type": "string",
         "pattern": "^[A-Z][A-Za-z0-9]*$"
      },
      "summary": {
         "type": "string"
      },
      "description": {
         "$ref": "./common.schema.json#/$defs/descriptionBlock"
      },
      "cullPrefix": {
         "type": "string",
         "pattern": "^[A-Z]{2,8}$",
         "not": {
            "const": "ANY"
         }
      },
      "attributes": {
         "type": "array",
         "minItems": 1,
         "items": {
            "$ref": "#/$defs/attribute"
         }
      }
   },
   "additionalProperties": true,
   "$defs": {
      "attribute": {
         "type": "object",
         "required": [
            "name",
            "summary",
            "description",
            "type",
            "flags"
         ],
         "properties": {
            "name": {
               "type": "string",
               "minLength": 1
            },
            "summary": {
               "type": "string",
               "minLength": 1
            },
            "description": {
               "$ref": "./common.schema.json#/$defs/descriptionBlock"
            },
            "type": {
               "$ref": "./common.schema.json#/$defs/attributeType"
            },
            "flags": {
               "$ref": "./common.schema.json#/$defs/flags"
            },
            "subClassName": {
               "type": "string"
            },
            "subCullPrefix": {
               "type": "string",
               "pattern": "^[A-Z]{2,8}$"
            }
         },
         "allOf": [
            {
               "if": {
                  "properties": {
                     "type": {
                        "enum": [
                           "lListT",
                           "lObjectT",
                           "lRefT"
                        ]
                     }
                  },
                  "required": ["type"]
               },
               "then": {
                  "required": [
                     "subClassName",
                     "subCullPrefix"
                  ]
               },
               "else": {
                  "not": {
                     "anyOf": [
                        { "required": ["subClassName"] },
                        { "required": ["subCullPrefix"] }
                     ]
                  }
               }
            }
         ],
         "additionalProperties": true
      }
   }
}

=== snowfrs/clusterscheduler/source/libs/sgeobj/json/FCAT.json
{
   "className": "FunctionalCategory",
   "summary": "Functional Category",
   "description": [
      {
         "line": "Objects of this type are used to sort the job list in the scheduler."
      },
      {
         "line": "All attributes are references to objects in other lists."
      }
   ],
   "cullPrefix": "FCAT",
   "attributes": [
      {
         "name": "job_share",
         "summary": "Job Share",
         "description": [
            {
               "line": "All jobs in this functional category have this amount of jobs shares."
            }
         ],
         "type": "lUlongT",
         "flags": []
      },
      {
         "name": "user_share",
         "summary": "User Share",
         "description": [
            {
               "line": "All jobs in this functional category have this amount of user shares."
            }
         ],
         "type": "lUlongT",
         "flags": []
      },
      {
         "name": "user",
         "summary": "User",
         "description": [
            {
               "line": "Pointer to the user structure."
            }
         ],
         "type": "lRefT",
         "subClassName": "ANY",
         "subCullPrefix": "ANY",
         "flags": []
      },
      {
         "name": "project_share",
         "summary": "Project Share",
         "description": [
            {
               "line": "All jobs in this functional category have this amount of project shares."
            }
         ],
         "type": "lUlongT",
         "flags": []
      },
      {
         "name": "project",
         "summary": "Project",
         "description": [
            {
               "line": "Pointer to the project structure."
            }
         ],
         "type": "lRefT",
         "subClassName": "ANY",
         "subCullPrefix": "ANY",
         "flags": []
      },
      {
         "name": "dept_share",
         "summary": "Department Share",
         "description": [
            {
               "line": "All jobs in this functional category have this amount of department shares."
            }
         ],
         "type": "lUlongT",
         "flags": []
      },
      {
         "name": "dept",
         "summary": "Department",
         "description": [
            {
               "line": "Pointer to the department structure."
            }
         ],
         "type": "lRefT",
         "subClassName": "ANY",
         "subCullPrefix": "ANY",
         "flags": []
      },
      {
         "name": "jobrelated_ticket_first",
         "summary": "First Job Related Ticket",
         "description": [
            {
               "line": "Pointer to the first element of job ticket list."
            }
         ],
         "type": "lRefT",
         "subClassName": "ANY",
         "subCullPrefix": "ANY",
         "flags": []
      },
      {
         "name": "jobrelated_ticket_last",
         "summary": "Last Job Related Ticket",
         "description": [
            {
               "line": "Pointer to the last element in the job ticket list."
            }
         ],
         "type": "lRefT",
         "subClassName": "ANY",
         "subCullPrefix": "ANY",
         "flags": []
      }
   ]
}

=== snowfrs/clusterscheduler/source/libs/sgeobj/json/LDR.json
{
   "className": "LoadReference",
   "summary": "@todo add summary",
   "description": [
      {
         "line": "@todo add description"
      }
   ],
   "cullPrefix": "LDR",
   "attributes": [
      {
         "name": "queue_ref_list",
         "summary": "@todo add summary",
         "description": [
            {
               "line": "@todo add description"
            }
         ],
         "type": "lListT",
         "subClassName": "QueueReference",
         "subCullPrefix": "QR",
         "flags": []
      },
      {
         "name": "limit",
         "summary": "@todo add summary",
         "description": [
            {
               "line": "@todo add description"
            }
         ],
         "type": "lStringT",
         "flags": []
      },
      {
         "name": "global",
         "summary": "@todo add summary",
         "description": [
            {
               "line": "@todo add description"
            }
         ],
         "type": "lRefT",
         "subClassName": "ANY",
         "subCullPrefix": "ANY",
         "flags": []
      },
      {
         "name": "host",
         "summary": "@todo add summary",
         "description": [
            {
               "line": "@todo add description"
            }
         ],
         "type": "lRefT",
         "subClassName": "ANY",
         "subCullPrefix": "ANY",
         "flags": []
      },
      {
         "name": "queue",
         "summary": "@todo add summary",
         "description": [
            {
               "line": "@todo add description"
            }
         ],
         "type": "lRefT",
         "subClassName": "ANY",
         "subCullPrefix": "ANY",
         "flags": []
      }
   ]
}

=== snowfrs/clusterscheduler/source/libs/sgeobj/json/CE.json
{
   "className": "ComplexEntry",
   "summary": "Complex Entry",
   "description": [
      {
         "line": "A complex entry contains a complex variable, both its definition as well as a possible current value"
      },
      {
         "line": "A complex variable is used for defining all types of attributes in Cluster Scheduler"
      },
      {
         "line": "as well as defining fixed values of resources and the capacity of consumable resources."
      },
      {
         "line": "@todo should be we better split definition and values into two objects?"
      }
   ],
   "cullPrefix": "CE",
   "attributes": [
      {
         "name": "name",
         "summary": "Full Name",
         "description": [
            {
               "line": "Full name of a complex variable."
            }
         ],
         "type": "lStringT",
         "flags": [
            {
               "name": "PRIMARY_KEY"
            },
            {
               "name": "UNIQUE"
            },
            {
               "name": "HASH"
            },
            {
               "name": "JGDI_CONF"
            },
            {
               "name": "SPOOL"
            },
            {
               "name": "SPOOL_SUBLIST"
            }
         ]
      },
      {
         "name": "shortcut",
         "summary": "Shortcut Name",
         "description": [
            {
               "line": "Shortcut for the complex variable name which can be used as an alternative to the name,"
            },
            {
               "line": "e.g. in job submission with qsub or when querying resources with qstat -F."
            }
         ],
         "type": "lStringT",
         "flags": [
            {
               "name": "UNIQUE"
            },
            {
               "name": "HASH"
            },
            {
               "name": "JGDI_CONF"
            },
            {
               "name": "SPOOL"
            }
         ]
      },
      {
         "name": "valtype",
         "summary": "Variable Type",
         "description": [
            {
               "line": "Type of the complex variable defined in common/basis_types.h, e.g."
            },
            {
               "line": "  - TYPE_INT"
            },
            {
               "line": "  - TYPE_STR"
            },
            {
               "line": "  - TYPE_TIM"
            },
            {
               "line": "  - TYPE_MEM"
            },
            {
               "line": "  - ..."
            },
            {
               "line": "@todo instead of defines, should we better use an enum?"
            }
         ],
         "type": "lUlongT",
         "flags": [
            {
               "name": "JGDI_CONF"
            },
            {
               "name": "SPOOL"
            }
         ]
      },
      {
         "name": "stringval",
         "summary": "String Value",
         "description": [
            {
               "line": "Value of the complex variable as string, from old docs: non overwritten value."
            }
         ],
         "type": "lStringT",
         "flags": [
            {
               "name": "JGDI_CONF"
            },
            {
               "name": "SPOOL"
            },
            {
               "name": "SPOOL_SUBLIST"
            }
         ]
      },
      {
         "name": "doubleval",
         "summary": "Double Value",
         "description": [
            {
               "line": "Value of the complex variable as double, from old docs: parsed CE_stringval"
            }
         ],
         "type": "lDoubleT",
         "flags": [
            {
               "name": "JGDI_HIDDEN"
            }
         ]
      },
      {
         "name": "relop",
         "summary": "Relational Operator",
         "description": [
            {
               "line": "Relational operator used in comparison of complex variables (e.g. against requests)."
            },
            {
               "line": "Defined in libs/sgeobj/sge_centry.h, e.g."
            },
            {
               "line": "CMPLXEQ_OP"
            },
            {
               "line": "CMPLXGE_OP"
            },
            {
               "line": "CMPLXGT_OP"
            },
            {
               "line": "..."
            }
         ],
         "type": "lUlongT",
         "flags": [
            {
               "name": "JGDI_CONF"
            },
            {
               "name": "SPOOL"
            }
         ]
      },
      {
         "name": "consumable",
         "summary": "Consumable Flag",
         "description": [
            {
               "line": "Defines if a complex variable is consumable and if it is a per job or per slot consumable."
            },
            {
               "line": "Defined in libs/sgeobj/sge_centry.h, possible values are"
            },
            {
               "line": "CONSUMABLE_NO"
            },
            {
               "line": "CONSUMABLE_YES"
            },
            {
               "line": "CONSUMABLE_JOB"
            },
            {
               "line": "CONSUMABLE_HOST"
            }
         ],
         "type": "lUlongT",
         "flags": [
            {
               "name": "JGDI_CONF"
            },
            {
               "name": "SPOOL"
            }
         ]
      },
      {
         "name": "defaultval",
         "summary": "Default Value",
         "description": [
            {
               "line": "Default value (default request) as string."
            }
         ],
         "type": "lStringT",
         "flags": [
            {
               "name": "JGDI_CONF"
            },
            {
               "name": "SPOOL"
            }
         ]
      },
      {
         "name": "dominant",
         "summary": "Monitoring Facility",
         "description": [
            {
               "line": "@todo add description"
            }
         ],
         "type": "lUlongT",
         "flags": [
            {
               "name": "JGDI_HIDDEN"
            }
         ]
      },
      {
         "name": "pj_stringval",
         "summary": "Per Job String Value",
         "description": [
            {
               "line": "Per job string value, @todo add more information"
            }
         ],
         "type": "lStringT",
         "flags": [
            {
               "name": "JGDI_HIDDEN"
            }
         ]
      },
      {
         "name": "pj_doubleval",
         "summary": "Per Job Double Value",
         "description": [
            {
               "line": "Per job double values, parsed from CE_stringval (?)"
            }
         ],
         "type": "lDoubleT",
         "flags": [
            {
               "name": "JGDI_HIDDEN"
            }
         ]
      },
      {
         "name": "pj_dominant",
         "summary": "Per Job Monitoring Facility",
         "description": [
            {
               "line": "@todo add description"
            }
         ],
         "type": "lUlongT",
         "flags": [
            {
               "name": "JGDI_HIDDEN"
            }
         ]
      },
      {
         "name": "requestable",
         "summary": "@todo add summary",
         "description": [
            {
               "line": "Defines if a complex variable can be requested and if it is a forced variable (must be requested)"
            },
            {
               "line": "Defined in libs/sgeobj/sge_centry.h, possible values are"
            },
            {
               "line": "REQU_NO"
            },
            {
               "line": "REQU_YES"
            },
            {
               "line": "REQU_FORCED"
            }
         ],
         "type": "lUlongT",
         "flags": [
            {
               "name": "JGDI_CONF"
            },
            {
               "name": "HASH"
            },
            {
               "name": "SPOOL"
            }
         ]
      },
      {
         "name": "tagged",
         "summary": "Variable Is Tagged",
         "description": [
            {
               "line": "Used for tagging variables, e.g. during the scheduling process."
            }
         ],
         "type": "lUlongT",
         "flags": [
            {
               "name": "JGDI_HIDDEN"
            }
         ]
      },
      {
         "name": "urgency_weight",
         "summary": "Urgency Weighting Factor",
         "description": [
            {
               "line": "Static Urgency Weighting Factor."
            }
         ],
         "type": "lStringT",
         "flags": [
            {
               "name": "JGDI_CONF"
            },
            {
               "name": "SPOOL"
            }
         ]
      },
      {
         "name": "resource_map_list",
         "summary": "Resource Map List",
         "description": [
            {
               "line": "on host level only: RSMAP id list"
            }
         ],
         "type": "lListT",
         "subClassName": "ResourceList",
         "subCullPrefix": "RESL",
         "flags": [
            {
               "name": "JGDI_CONF"
            },
            {
               "name": "SPOOL"
            }
         ]
      }
   ]
}

=== snowfrs/clusterscheduler/source/libs/sgeobj/json/UE.json
{
   "className": "UserSetEntry",
   "summary": "UserSet Entry",
   "description": [
      {
         "line": "An object of this type represents one entry in an user set."
      }
   ],
   "cullPrefix": "UE",
   "attributes": [
      {
         "name": "name",
         "summary": "User or Group name",
         "description": [
            {
               "line": "Name of an user or a UNIX user group. Groups have the prefix @, e.g. @tape"
            }
         ],
         "type": "lStringT",
         "flags": [
            {
               "name": "PRIMARY_KEY"
            },
            {
               "name": "UNIQUE"
            },
            {
               "name": "HASH"
            },
            {
               "name": "SPOOL_SUBLIST"
            }
         ]
      }
   ]
}

=== snowfrs/clusterscheduler/source/libs/sgeobj/json/SPR.json
{
   "className": "SpoolingRule",
   "summary": "Spooling Rule",
   "description": [
      {
         "line": "A spooling rule describes a certain way to store and retrieve"
      },
      {
         "line": "data from a defined storage facility."
      },
      {
         "line": " "
      },
      {
         "line": "Spooling rules can implement spooling to files in a certain"
      },
      {
         "line": "directory or spooling into a database, to an LDAP repository, etc."
      },
      {
         "line": " "
      },
      {
         "line": "A spooling context can contain multiple spooling rules."
      }
   ],
   "cullPrefix": "SPR",
   "attributes": [
      {
         "name": "name",
         "summary": "Name",
         "description": [
            {
               "line": "Unique name of the rule."
            }
         ],
         "type": "lStringT",
         "flags": [
            {
               "name": "UNIQUE"
            },
            {
               "name": "HASH"
            }
         ]
      },
      {
         "name": "url",
         "summary": "URL",
         "description": [
            {
               "line": "An url, e.g. a spool directory, a database url etc."
            }
         ],
         "type": "lStringT",
         "flags": []
      },
      {
         "name": "option_func",
         "summary": "Option Function",
         "description": [
            {
               "line": "Function pointer to a function to set any database specific options,"
            },
            {
               "line": "e.g. whether to do database recovery at startup or not."
            }
         ],
         "type": "lRefT",
         "subClassName": "ANY",
         "subCullPrefix": "ANY",
         "flags": []
      },
      {
         "name": "startup_func",
         "summary": "Startup Function",
         "description": [
            {
               "line": "Function pointer to a startup function,"
            },
            {
               "line": "e.g. establishing a connection to a database."
            }
         ],
         "type": "lRefT",
         "subClassName": "ANY",
         "subCullPrefix": "ANY",
         "flags": []
      },
      {
         "name": "shutdown_func",
         "summary": "Shutdown Function",
         "description": [
            {
               "line": "Function pointer to a shutdown function,"
            },
            {
               "line": "e.g. disconnecting from a database or closing file handles."
            }
         ],
         "type": "lRefT",
         "subClassName": "ANY",
         "subCullPrefix": "ANY",
         "flags": []
      },
      {
         "name": "maintenance_func",
         "summary": "Maintenance Function",
         "description": [
            {
               "line": "Function pointer to a maintenance function for"
            },
            {
               "line": "- creating the database tables / directories in case of filebased spooling"
            },
            {
               "line": "- switching between spooling with/without history"
            },
            {
               "line": "- backup"
            },
            {
               "line": "- cleaning up / compressing database"
            },
            {
               "line": "- etc."
            }
         ],
         "type": "lRefT",
         "subClassName": "ANY",
         "subCullPrefix": "ANY",
         "flags": []
      },
      {
         "name": "trigger_func",
         "summary": "Trigger Function",
         "description": [
            {
               "line": "Function pointer to a trigger function."
            },
            {
               "line": "A trigger function is used to trigger regular actions, e.g."
            },
            {
               "line": "checkpointing and cleaning the transaction log in case of the"
            },
            {
               "line": "Berkeley DB or vacuuming in case of PostgreSQL."
            }
         ],
         "type": "lRefT",
         "subClassName": "ANY",
         "subCullPrefix": "ANY",
         "flags": []
      },
      {
         "name": "transaction_func",
         "summary": "Transaction Function",
         "description": [
            {
               "line": "Function pointer to a function beginning and ending transactions."
            },
            {
               "line": " "
            }
         ],
         "type": "lRefT",
         "subClassName": "ANY",
         "subCullPrefix": "ANY",
         "flags": []
      },
      {
         "name": "list_func",
         "summary": "List Function",
         "description": [
            {
               "line": "Pointer to a function reading complete lists (master lists)"
            },
            {
               "line": "from the spooling data source."
            }
         ],
         "type": "lRefT",
         "subClassName": "ANY",
         "subCullPrefix": "ANY",
         "flags": []
      },
      {
         "name": "read_func",
         "summary": "Read Function",
         "description": [
            {
               "line": "Pointer to a function reading a single object from the"
            },
            {
               "line": "spooling data source."
            }
         ],
         "type": "lRefT",
         "subClassName": "ANY",
         "subCullPrefix": "ANY",
         "flags": []
      },
      {
         "name": "read_keys_func",
         "summary": "Read Keys Function",
         "description": [
            {
               "line": "Reads all keys from a spooling database"
            },
            {
               "line": "matching beginning with a certain pattern."
            },
            {
               "line": "@see e.g. spool_berkeleydb_read_keys()"
            }
         ],
         "type": "lRefT",
         "subClassName": "ANY",
         "subCullPrefix": "ANY",
         "flags": []
      },
      {
         "name": "write_func",
         "summary": "Write Function",
         "description": [
            {
               "line": "Pointer to a function writing a single object."
            }
         ],
         "type": "lRefT",
         "subClassName": "ANY",
         "subCullPrefix": "ANY",
         "flags": []
      },
      {
         "name": "delete_func",
         "summary": "Delete Function",
         "description": [
            {
               "line": "Pointer to a function deleting a single object."
            },
            {
               "line": " "
            }
         ],
         "type": "lRefT",
         "subClassName": "ANY",
         "subCullPrefix": "ANY",
         "flags": []
      },
      {
         "name": "validate_func",
         "summary": "Validate Function",
         "description": [
            {
               "line": "Pointer to a function validating a single object."
            }
         ],
         "type": "lRefT",
         "subClassName": "ANY",
         "subCullPrefix": "ANY",
         "flags": []
      },
      {
         "name": "validate_list_func",
         "summary": "Validate List Function",
         "description": [
            {
               "line": "Pointer to a function validating a list of objects."
            },
            {
               "line": " "
            }
         ],
         "type": "lRefT",
         "subClassName": "ANY",
         "subCullPrefix": "ANY",
         "flags": []
      },
      {
         "name": "clientdata",
         "summary": "Client Data",
         "description": [
            {
               "line": "Clientdata; any pointer, can be used to store and"
            },
            {
               "line": "reference rule specific data, e.g. file or database handles."
            }
         ],
         "type": "lRefT",
         "subClassName": "ANY",
         "subCullPrefix": "ANY",
         "flags": []
      }
   ]
}

=== snowfrs/clusterscheduler/source/libs/sgeobj/json/LR.json
{
   "className": "LoadReport",
   "summary": "Load Report",
   "description": [
      {
         "line": "A LoadReport object represents the value for a single load variable on a specific host."
      }
   ],
   "cullPrefix": "LR",
   "attributes": [
      {
         "name": "name",
         "summary": "Load Variable Name",
         "description": [
            {
               "line": "Name of the load variable. In order for the load value to be processed in sge_qmaster"
            },
            {
               "line": "a complex variable with this name must have been configured."
            }
         ],
         "type": "lStringT",
         "flags": [
            {
               "name": "HASH"
            }
         ]
      },
      {
         "name": "value",
         "summary": "Load Variable Value",
         "description": [
            {
               "line": "Value of the variable on a specific host."
            }
         ],
         "type": "lStringT",
         "flags": []
      },
      {
         "name": "global",
         "summary": "Is Global",
         "description": [
            {
               "line": "Specifies if it is a global load variable."
            },
            {
               "line": "1 means that it is a global load value (host is global in this case),"
            },
            {
               "line": "0 means that it is a host specific load value."
            },
            {
               "line": "@todo: make it a boolean"
            }
         ],
         "type": "lUlongT",
         "flags": []
      },
      {
         "name": "is_static",
         "summary": "Is Static",
         "description": [
            {
               "line": "Specifies if it is a static load variable."
            },
            {
               "line": "Static load variables represent seldomly changing variables, e.g. arch, n_proc, mem_total."
            },
            {
               "line": "0 means a non static load value"
            },
            {
               "line": "1 means a static load value"
            },
            {
               "line": "2 is a special internal value: remove the load value"
            }
         ],
         "type": "lUlongT",
         "flags": []
      },
      {
         "name": "host",
         "summary": "Host Name",
         "description": [
            {
               "line": "Name of the host on which the load value is valid. Specific host name or keyword global for global load values."
            }
         ],
         "type": "lHostT",
         "flags": [
            {
               "name": "HASH"
            }
         ]
      }
   ]
}
