=== snowfrs/clusterscheduler/source/dist/util/resources/json-schemas/definition-file.schema.json
{
   "$schema": "https://json-schema.org/draft/2020-12/schema",
   "$id": "https://github.com/hpc-gridware/clusterscheduler/tree/master/source/dist/util/resources/json-schemas/definition-file.schema.json",
   "type": "object",
   "required": [
      "className",
      "summary",
      "description",
      "cullPrefix",
      "attributes"
   ],
   "properties": {
      "className": {
         "type": "string",
         "pattern": "^[A-Z][A-Za-z0-9]*$"
      },
      "summary": {
         "type": "string"
      },
      "description": {
         "$ref": "./common.schema.json#/$defs/descriptionBlock"
      },
      "cullPrefix": {
         "type": "string",
         "pattern": "^[A-Z]{2,8}$",
         "not": {
            "const": "ANY"
         }
      },
      "attributes": {
         "type": "array",
         "minItems": 1,
         "items": {
            "$ref": "#/$defs/attribute"
         }
      }
   },
   "additionalProperties": true,
   "$defs": {
      "attribute": {
         "type": "object",
         "required": [
            "name",
            "summary",
            "description",
            "type",
            "flags"
         ],
         "properties": {
            "name": {
               "type": "string",
               "minLength": 1
            },
            "summary": {
               "type": "string",
               "minLength": 1
            },
            "description": {
               "$ref": "./common.schema.json#/$defs/descriptionBlock"
            },
            "type": {
               "$ref": "./common.schema.json#/$defs/attributeType"
            },
            "flags": {
               "$ref": "./common.schema.json#/$defs/flags"
            },
            "subClassName": {
               "type": "string"
            },
            "subCullPrefix": {
               "type": "string",
               "pattern": "^[A-Z]{2,8}$"
            }
         },
         "allOf": [
            {
               "if": {
                  "properties": {
                     "type": {
                        "enum": [
                           "lListT",
                           "lObjectT",
                           "lRefT"
                        ]
                     }
                  },
                  "required": ["type"]
               },
               "then": {
                  "required": [
                     "subClassName",
                     "subCullPrefix"
                  ]
               },
               "else": {
                  "not": {
                     "anyOf": [
                        { "required": ["subClassName"] },
                        { "required": ["subCullPrefix"] }
                     ]
                  }
               }
            }
         ],
         "additionalProperties": true
      }
   }
}

=== snowfrs/clusterscheduler/source/libs/sgeobj/json/QAJ.json
{
   "className": "AccountingSummary",
   "summary": "Accounting Summary",
   "description": [
      {
         "line": "Used in qsub for summing up usage values (?)."
      },
      {
         "line": "It contains some of the fields which can appear in the qacct -j job_id output."
      },
      {
         "line": "See also the sge_accounting(5) man page."
      }
   ],
   "cullPrefix": "QAJ",
   "attributes": [
      {
         "name": "host",
         "summary": "Host Name",
         "description": [
            {
               "line": "Host where a job ran."
            }
         ],
         "type": "lHostT",
         "flags": []
      },
      {
         "name": "queue",
         "summary": "Cluster Queue Name",
         "description": [
            {
               "line": "Cluster queue in which a job ran."
            }
         ],
         "type": "lStringT",
         "flags": []
      },
      {
         "name": "group",
         "summary": "User Group",
         "description": [
            {
               "line": "Unix user group of the job owner."
            }
         ],
         "type": "lStringT",
         "flags": []
      },
      {
         "name": "owner",
         "summary": "Owner",
         "description": [
            {
               "line": "Unix user name of the job owner."
            }
         ],
         "type": "lStringT",
         "flags": []
      },
      {
         "name": "project",
         "summary": "Project",
         "description": [
            {
               "line": "Project the job was running for."
            }
         ],
         "type": "lStringT",
         "flags": []
      },
      {
         "name": "department",
         "summary": "Department",
         "description": [
            {
               "line": "The job owner's department."
            }
         ],
         "type": "lStringT",
         "flags": []
      },
      {
         "name": "ru_wallclock",
         "summary": "Rusage Wallclock",
         "description": [
            {
               "line": "Wallclock time from rusage (end time - start_time)."
            }
         ],
         "type": "lDoubleT",
         "flags": []
      },
      {
         "name": "ru_utime",
         "summary": "Rusage User Time",
         "description": [
            {
               "line": "User CPU time from rusage."
            }
         ],
         "type": "lDoubleT",
         "flags": []
      },
      {
         "name": "ru_stime",
         "summary": "Rusage System Time",
         "description": [
            {
               "line": "System CPU time from rusage."
            }
         ],
         "type": "lDoubleT",
         "flags": []
      },
      {
         "name": "ru_maxrss",
         "summary": "Rusage Maximum RSS",
         "description": [
            {
               "line": "Maximum resident set size of the job's processes from rusage."
            }
         ],
         "type": "lDoubleT",
         "flags": []
      },
      {
         "name": "ru_inblock",
         "summary": "Rusage Block Input",
         "description": [
            {
               "line": "Number of block input operations from rusage."
            }
         ],
         "type": "lDoubleT",
         "flags": []
      },
      {
         "name": "granted_pe",
         "summary": "Granted Parallel Environment",
         "description": [
            {
               "line": "In case of a parallel job: The PE the job was running in."
            }
         ],
         "type": "lStringT",
         "flags": []
      },
      {
         "name": "slots",
         "summary": "Slots",
         "description": [
            {
               "line": "The number of slots the job occupied."
            }
         ],
         "type": "lUlongT",
         "flags": []
      },
      {
         "name": "cpu",
         "summary": "Cpu Usage",
         "description": [
            {
               "line": "The cpu usage of the job reported by sge_execd in seconds."
            }
         ],
         "type": "lDoubleT",
         "flags": []
      },
      {
         "name": "mem",
         "summary": "Integral Memory Usage",
         "description": [
            {
               "line": "The integral memory usage of the job reported by sge_execd in Gbytes cpu seconds."
            }
         ],
         "type": "lDoubleT",
         "flags": []
      },
      {
         "name": "io",
         "summary": "IO Usage",
         "description": [
            {
               "line": "The IO usage of the job reported by sge_execd (the amount of data transferred in input and output operations."
            }
         ],
         "type": "lDoubleT",
         "flags": []
      },
      {
         "name": "iow",
         "summary": "IO Wait Time",
         "description": [
            {
               "line": "The amount of time the job waited for IO operations to happen as reported by sge_execd."
            }
         ],
         "type": "lDoubleT",
         "flags": []
      },
      {
         "name": "maxvmem",
         "summary": "Maximum Virtual Memory",
         "description": [
            {
               "line": "The maximum virtual memory usage of the job reported by sge_execd."
            }
         ],
         "type": "lDoubleT",
         "flags": []
      },
      {
         "name": "arid",
         "summary": "AR Id",
         "description": [
            {
               "line": "The id of an advance reservation the job might have run in."
            }
         ],
         "type": "lUlongT",
         "flags": []
      }
   ]
}

=== snowfrs/clusterscheduler/source/libs/sgeobj/json/ACK.json
{
   "className": "Acknowledge",
   "summary": "@todo add summary",
   "description": [
      {
         "line": "@todo add description"
      }
   ],
   "cullPrefix": "ACK",
   "attributes": [
      {
         "name": "type",
         "summary": "@todo add summary",
         "description": [
            {
               "line": "@todo add description"
            }
         ],
         "type": "lUlongT",
         "flags": [
            {
               "name": "JGDI_HIDDEN"
            }
         ]
      },
      {
         "name": "id",
         "summary": "@todo add summary",
         "description": [
            {
               "line": "@todo add description"
            }
         ],
         "type": "lUlongT",
         "flags": [
            {
               "name": "JGDI_HIDDEN"
            }
         ]
      },
      {
         "name": "id2",
         "summary": "@todo add summary",
         "description": [
            {
               "line": "@todo add description"
            }
         ],
         "type": "lUlongT",
         "flags": [
            {
               "name": "JGDI_HIDDEN"
            }
         ]
      },
      {
         "name": "str",
         "summary": "@todo add summary",
         "description": [
            {
               "line": "@todo add description"
            }
         ],
         "type": "lStringT",
         "flags": [
            {
               "name": "JGDI_HIDDEN"
            }
         ]
      }
   ]
}

=== snowfrs/clusterscheduler/source/libs/sgeobj/json/MR.json
{
   "className": "MailReceiver",
   "summary": "Mail Receiver",
   "description": [
      {
         "line": "One object of this type specifies a mail receiver, meaning an email address"
      },
      {
         "line": "in the form user@host."
      },
      {
         "line": "It is used e.g. when submitting jobs via qsub -M user[@host][,user[@host],...]"
      },
      {
         "line": "@todo why do we split it into user and host? We could just have a single string holding an email address."
      }
   ],
   "cullPrefix": "MR",
   "attributes": [
      {
         "name": "user",
         "summary": "User Name",
         "description": [
            {
               "line": "User name of the mail receipient"
            }
         ],
         "type": "lStringT",
         "flags": [
            {
               "name": "PRIMARY_KEY"
            },
            {
               "name": "SPOOL_SUBLIST"
            }
         ]
      },
      {
         "name": "host",
         "summary": "Host Name",
         "description": [
            {
               "line": "Host / Domain part of a mail receipient."
            }
         ],
         "type": "lHostT",
         "flags": [
            {
               "name": "SPOOL_SUBLIST"
            }
         ]
      }
   ]
}

=== snowfrs/clusterscheduler/source/libs/sgeobj/json/CCT.json
{
   "className": "CategoryCache",
   "summary": "@todo add summary",
   "description": [
      {
         "line": "@todo add description"
      }
   ],
   "cullPrefix": "CCT",
   "attributes": [
      {
         "name": "pe_name",
         "summary": "@todo add summary",
         "description": [
            {
               "line": "@todo add description"
            }
         ],
         "type": "lStringT",
         "flags": []
      },
      {
         "name": "ignore_queues",
         "summary": "@todo add summary",
         "description": [
            {
               "line": "@todo add description"
            }
         ],
         "type": "lListT",
         "subClassName": "SkipListEntry",
         "subCullPrefix": "CTI",
         "flags": []
      },
      {
         "name": "ignore_hosts",
         "summary": "@todo add summary",
         "description": [
            {
               "line": "@todo add description"
            }
         ],
         "type": "lListT",
         "subClassName": "SkipListEntry",
         "subCullPrefix": "CTI",
         "flags": []
      },
      {
         "name": "job_messages",
         "summary": "@todo add summary",
         "description": [
            {
               "line": "@todo add description"
            }
         ],
         "type": "lListT",
         "subClassName": "JobSchedulingMessage",
         "subCullPrefix": "MES",
         "flags": []
      },
      {
         "name": "pe_job_slots",
         "summary": "@todo add summary",
         "description": [
            {
               "line": "@todo add description"
            }
         ],
         "type": "lRefT",
         "subClassName": "ANY",
         "subCullPrefix": "ANY",
         "flags": []
      },
      {
         "name": "pe_job_slot_count",
         "summary": "@todo add summary",
         "description": [
            {
               "line": "@todo add description"
            }
         ],
         "type": "lUlongT",
         "flags": []
      }
   ]
}

=== snowfrs/clusterscheduler/source/libs/sgeobj/json/CK.json
{
   "className": "Checkpoint",
   "summary": "Checkpoint",
   "description": [
      {
         "line": "This is the list type to hold the checkpointing object"
      },
      {
         "line": "for the interfaces to the various supported checkpointing mechanisms."
      }
   ],
   "cullPrefix": "CK",
   "attributes": [
      {
         "name": "name",
         "summary": "Name",
         "description": [
            {
               "line": "@todo add description"
            }
         ],
         "type": "lStringT",
         "flags": [
            {
               "name": "PRIMARY_KEY"
            },
            {
               "name": "UNIQUE"
            },
            {
               "name": "HASH"
            },
            {
               "name": "JGDI_CONF"
            },
            {
               "name": "SPOOL"
            }
         ]
      },
      {
         "name": "interface",
         "summary": "Interface",
         "description": [
            {
               "line": "The type of checkpointing to be used, e.g."
            },
            {
               "line": " -hibernator"
            },
            {
               "line": " -cpr @todo no longer supported SGI kernel level checkpointing, remove"
            },
            {
               "line": " -cray-ckpt @todo no longer supported Cray kernel level checkpointing, remove"
            },
            {
               "line": " -transparent, using a checkpointing library like Condor"
            },
            {
               "line": " -userdefined, some user defined method"
            },
            {
               "line": " -application-level, same as userdefined, all interface commands except restart are used, @todo verify"
            }
         ],
         "type": "lStringT",
         "flags": [
            {
               "name": "JGDI_CONF"
            },
            {
               "name": "SPOOL"
            }
         ]
      },
      {
         "name": "ckpt_command",
         "summary": "Checkpoint Command",
         "description": [
            {
               "line": "Commandline to be executed to initiate a checkpoint."
            }
         ],
         "type": "lStringT",
         "flags": [
            {
               "name": "JGDI_CONF"
            },
            {
               "name": "SPOOL"
            }
         ]
      },
      {
         "name": "migr_command",
         "summary": "Migration Command",
         "description": [
            {
               "line": "Commandline to be executed to initiate a migration of a job (from one host to another one)."
            }
         ],
         "type": "lStringT",
         "flags": [
            {
               "name": "JGDI_CONF"
            },
            {
               "name": "SPOOL"
            }
         ]
      },
      {
         "name": "rest_command",
         "summary": "Restart Command",
         "description": [
            {
               "line": "Commandline to be executed to restart a checkpointed application."
            }
         ],
         "type": "lStringT",
         "flags": [
            {
               "name": "JGDI_CONF"
            },
            {
               "name": "SPOOL"
            }
         ]
      },
      {
         "name": "ckpt_dir",
         "summary": "Checkpoint Directory",
         "description": [
            {
               "line": "A directory to which checkpoints shall be written."
            }
         ],
         "type": "lStringT",
         "flags": [
            {
               "name": "JGDI_CONF"
            },
            {
               "name": "SPOOL"
            }
         ]
      },
      {
         "name": "when",
         "summary": "When",
         "description": [
            {
               "line": "When a checkpoint shall be written, one or a combination of:"
            },
            {
               "line": " n: no checkpoint is performed"
            },
            {
               "line": " s: when the execution service is shutdown"
            },
            {
               "line": " m: checkpoint every minimum CPU interval (see queue configuration)"
            },
            {
               "line": " x: when the job gets suspended"
            },
            {
               "line": " an interval: in the specified interval"
            }
         ],
         "type": "lStringT",
         "flags": [
            {
               "name": "JGDI_CONF"
            },
            {
               "name": "SPOOL"
            }
         ]
      },
      {
         "name": "signal",
         "summary": "Signal",
         "description": [
            {
               "line": "A Unix signal to be sent to the jobs process(es) in order to initiate a checkpoint."
            }
         ],
         "type": "lStringT",
         "flags": [
            {
               "name": "JGDI_CONF"
            },
            {
               "name": "SPOOL"
            }
         ]
      },
      {
         "name": "job_pid",
         "summary": "Job Pid",
         "description": [
            {
               "line": "@todo not used and can be removed?"
            }
         ],
         "type": "lUlongT",
         "flags": [
            {
               "name": "JGDI_HIDDEN"
            }
         ]
      },
      {
         "name": "clean_command",
         "summary": "Clean Command",
         "description": [
            {
               "line": "Commandline to be executed after checkpointing to clean up."
            }
         ],
         "type": "lStringT",
         "flags": [
            {
               "name": "JGDI_CONF"
            },
            {
               "name": "SPOOL"
            }
         ]
      },
      {
         "name": "joker",
         "summary": "Joker",
         "description": [
            {
               "line": "Placeholder which can be used for arbitrary data."
            },
            {
               "line": "Its purpose is to be able to add new attributes without changing the spooling format."
            },
            {
               "line": "It is a list of arbitrary type and it is spooled."
            }
         ],
         "type": "lListT",
         "subClassName": "Variable",
         "subCullPrefix": "VA",
         "flags": [
            {"name": "SPOOL"}
         ]
      }
   ]
}

=== snowfrs/clusterscheduler/source/libs/sgeobj/json/STU.json
{
   "className": "UniqueString",
   "summary": "Unique String",
   "description": [
      {
         "line": "An object of this type holds a string which is unique in a List of STU_Type."
      }
   ],
   "cullPrefix": "STU",
   "attributes": [
      {
         "name": "name",
         "summary": "String Name",
         "description": [
            {
               "line": "String contents."
            }
         ],
         "type": "lStringT",
         "flags": [
            {
               "name": "PRIMARY_KEY"
            },
            {
               "name": "UNIQUE"
            },
            {
               "name": "HASH"
            },
            {
               "name": "SPOOL_SUBLIST"
            }
         ]
      }
   ]
}

=== snowfrs/clusterscheduler/source/libs/sgeobj/json/PARA.json
{
   "className": "SchedulerConfigParameter",
   "summary": "@todo add summary",
   "description": [
      {
         "line": "@todo add description"
      }
   ],
   "cullPrefix": "PARA",
   "attributes": [
      {
         "name": "name",
         "summary": "@todo add summary",
         "description": [
            {
               "line": "@todo add description"
            }
         ],
         "type": "lStringT",
         "flags": [
            {
               "name": "PRIMARY_KEY"
            }
         ]
      },
      {
         "name": "value",
         "summary": "@todo add summary",
         "description": [
            {
               "line": "@todo add description"
            }
         ],
         "type": "lStringT",
         "flags": []
      }
   ]
}

=== snowfrs/clusterscheduler/source/libs/sgeobj/json/JL.json
{
   "className": "PtfJob",
   "summary": "PTF Job",
   "description": [
      {
         "line": "This is the list type we use to hold the jobs which are running under the local execution daemon."
      },
      {
         "line": "@todo This is a very old module and probably noone really knows its details any more. Add better documentation."
      }
   ],
   "cullPrefix": "JL",
   "attributes": [
      {
         "name": "job_ID",
         "summary": "Job Id",
         "description": [
            {
               "line": "The Job Id."
            }
         ],
         "type": "lUlongT",
         "flags": [
            {
               "name": "PRIMARY_KEY"
            },
            {
               "name": "UNIQUE"
            },
            {
               "name": "HASH"
            }
         ]
      },
      {
         "name": "OS_job_list",
         "summary": "OS Job List",
         "description": [
            {
               "line": "List of OS jobs (JO_Type). There should be one per running Array/PE task having one os job id each."
            }
         ],
         "type": "lListT",
         "subClassName": "JO",
         "subCullPrefix": "JO",
         "flags": []
      },
      {
         "name": "state",
         "summary": "State",
         "description": [
            {
               "line": "Job State, one of JL_JOB_ACTIVE, JL_JOB_COMPLETE, JL_JOB_DELETED."
            }
         ],
         "type": "lUlongT",
         "flags": []
      },
      {
         "name": "tickets",
         "summary": "Tickets",
         "description": [
            {
               "line": "Job Tickets. Used for reprioritization."
            }
         ],
         "type": "lUlongT",
         "flags": []
      },
      {
         "name": "share",
         "summary": "Share",
         "description": [
            {
               "line": "ptf interval share"
            }
         ],
         "type": "lDoubleT",
         "flags": []
      },
      {
         "name": "ticket_share",
         "summary": "Ticket Share",
         "description": [
            {
               "line": "ptf job ticket share"
            }
         ],
         "type": "lDoubleT",
         "flags": []
      },
      {
         "name": "timeslice",
         "summary": "Timeslice",
         "description": [
            {
               "line": "ptf calculated timeslice (SX)"
            }
         ],
         "type": "lDoubleT",
         "flags": []
      },
      {
         "name": "usage",
         "summary": "Usage",
         "description": [
            {
               "line": "ptf interval combined usage"
            }
         ],
         "type": "lDoubleT",
         "flags": []
      },
      {
         "name": "old_usage_value",
         "summary": "Old Usage",
         "description": [
            {
               "line": "ptf interval combined usage"
            }
         ],
         "type": "lDoubleT",
         "flags": []
      },
      {
         "name": "adjusted_usage",
         "summary": "Adjusted Usage",
         "description": [
            {
               "line": "ptf interval adjusted usage"
            }
         ],
         "type": "lDoubleT",
         "flags": []
      },
      {
         "name": "last_usage",
         "summary": "Last Usage",
         "description": [
            {
               "line": "ptf last interval combined usage"
            }
         ],
         "type": "lDoubleT",
         "flags": []
      },
      {
         "name": "old_usage",
         "summary": "Old Usage",
         "description": [
            {
               "line": "prev interval combined usage"
            }
         ],
         "type": "lDoubleT",
         "flags": []
      },
      {
         "name": "proportion",
         "summary": "Proportion",
         "description": [
            {
               "line": "@todo add description"
            }
         ],
         "type": "lDoubleT",
         "flags": []
      },
      {
         "name": "adjusted_proportion",
         "summary": "Adjusted Proportion",
         "description": [
            {
               "line": "@todo add description"
            }
         ],
         "type": "lDoubleT",
         "flags": []
      },
      {
         "name": "adjusted_current_proportion",
         "summary": "Adjusted Current Proportion",
         "description": [
            {
               "line": "@todo add description"
            }
         ],
         "type": "lDoubleT",
         "flags": []
      },
      {
         "name": "actual_proportion",
         "summary": "Actual Proportion",
         "description": [
            {
               "line": "@todo add description"
            }
         ],
         "type": "lDoubleT",
         "flags": []
      },
      {
         "name": "diff_proportion",
         "summary": "Diff Proportion",
         "description": [
            {
               "line": "@todo add description"
            }
         ],
         "type": "lDoubleT",
         "flags": []
      },
      {
         "name": "last_proportion",
         "summary": "Last Proportion",
         "description": [
            {
               "line": "@todo add description"
            }
         ],
         "type": "lDoubleT",
         "flags": []
      },
      {
         "name": "curr_pri",
         "summary": "Current Priority",
         "description": [
            {
               "line": "@todo add description"
            }
         ],
         "type": "lDoubleT",
         "flags": []
      },
      {
         "name": "pri",
         "summary": "Priority",
         "description": [
            {
               "line": "@todo add description"
            }
         ],
         "type": "lLongT",
         "flags": []
      },
      {
         "name": "procfd",
         "summary": "Proc FD",
         "description": [
            {
               "line": "proc file descriptor"
            }
         ],
         "type": "lUlongT",
         "flags": []
      },
      {
         "name": "interactive",
         "summary": "Interactive",
         "description": [
            {
               "line": "interactive flag"
            }
         ],
         "type": "lUlongT",
         "flags": []
      }
   ]
}
