=== snowfrs/clusterscheduler/source/dist/util/resources/json-schemas/definition-file.schema.json
{
   "$schema": "https://json-schema.org/draft/2020-12/schema",
   "$id": "https://github.com/hpc-gridware/clusterscheduler/tree/master/source/dist/util/resources/json-schemas/definition-file.schema.json",
   "type": "object",
   "required": [
      "className",
      "summary",
      "description",
      "cullPrefix",
      "attributes"
   ],
   "properties": {
      "className": {
         "type": "string",
         "pattern": "^[A-Z][A-Za-z0-9]*$"
      },
      "summary": {
         "type": "string"
      },
      "description": {
         "$ref": "./common.schema.json#/$defs/descriptionBlock"
      },
      "cullPrefix": {
         "type": "string",
         "pattern": "^[A-Z]{2,8}$",
         "not": {
            "const": "ANY"
         }
      },
      "attributes": {
         "type": "array",
         "minItems": 1,
         "items": {
            "$ref": "#/$defs/attribute"
         }
      }
   },
   "additionalProperties": true,
   "$defs": {
      "attribute": {
         "type": "object",
         "required": [
            "name",
            "summary",
            "description",
            "type",
            "flags"
         ],
         "properties": {
            "name": {
               "type": "string",
               "minLength": 1
            },
            "summary": {
               "type": "string",
               "minLength": 1
            },
            "description": {
               "$ref": "./common.schema.json#/$defs/descriptionBlock"
            },
            "type": {
               "$ref": "./common.schema.json#/$defs/attributeType"
            },
            "flags": {
               "$ref": "./common.schema.json#/$defs/flags"
            },
            "subClassName": {
               "type": "string"
            },
            "subCullPrefix": {
               "type": "string",
               "pattern": "^[A-Z]{2,8}$"
            }
         },
         "allOf": [
            {
               "if": {
                  "properties": {
                     "type": {
                        "enum": [
                           "lListT",
                           "lObjectT",
                           "lRefT"
                        ]
                     }
                  },
                  "required": ["type"]
               },
               "then": {
                  "required": [
                     "subClassName",
                     "subCullPrefix"
                  ]
               },
               "else": {
                  "not": {
                     "anyOf": [
                        { "required": ["subClassName"] },
                        { "required": ["subCullPrefix"] }
                     ]
                  }
               }
            }
         ],
         "additionalProperties": true
      }
   }
}

=== snowfrs/clusterscheduler/source/libs/sgeobj/json/JRS.json
{
   "className": "JobRequestSet",
   "summary": "Job Request Set",
   "description": [
      {
         "line": "A job request set contains job requests (currently: queue requests and resource requests)"
      },
      {
         "line": "valid for a specific scope of parallel tasks (global, master, slaves)."
      },
      {
         "line": "Sequential jobs can have a single job request set, the global one."
      },
      {
         "line": "Parallel jobs can have up to 3 request sets, global requests, requests for the master task,"
      },
      {
         "line": "requests for the slave tasks."
      },
      {
         "line": "None of them must exist, every one can exist, depending on requests"
      }
   ],
   "cullPrefix": "JRS",
   "attributes": [
      {
         "name": "scope",
         "summary": "Scope",
         "description": [
            {
               "line": "Request scope: global, master, slaves."
            }
         ],
         "type": "lUlongT",
         "flags": [
            {
               "name": "PRIMARY_KEY"
            },
            {
               "name": "UNIQUE"
            },
            {
               "name": "SPOOL"
            }
         ]
      },
      {
         "name": "hard_resource_list",
         "summary": "Hard Resource List",
         "description": [
            {
               "line": "List of hard resource requests, from qsub -l name=value request."
            }
         ],
         "type": "lListT",
         "subClassName": "ComplexEntry",
         "subCullPrefix": "CE",
         "flags": [
            {
               "name": "SPOOL"
            }
         ]
      },
      {
         "name": "soft_resource_list",
         "summary": "Soft Resource List",
         "description": [
            {
               "line": "List of soft resource requests, from qsub -soft -l name=value request."
            }
         ],
         "type": "lListT",
         "subClassName": "ComplexEntry",
         "subCullPrefix": "CE",
         "flags": [
            {
               "name": "SPOOL"
            }
         ]
      },
      {
         "name": "hard_queue_list",
         "summary": "Hard Queue List",
         "description": [
            {
               "line": "List of hard queue requests, from qsub -q dest_identifier request."
            }
         ],
         "type": "lListT",
         "subClassName": "QueueReference",
         "subCullPrefix": "QR",
         "flags": [
            {
               "name": "SPOOL"
            }
         ]
      },
      {
         "name": "soft_queue_list",
         "summary": "Soft Queue List",
         "description": [
            {
               "line": "List of soft queue requests, from qsub -soft -q dest_identifier request."
            }
         ],
         "type": "lListT",
         "subClassName": "QueueReference",
         "subCullPrefix": "QR",
         "flags": [
            {
               "name": "SPOOL"
            }
         ]
      },
      {
         "name": "allocation_rule",
         "summary": "Allocation Rule",
         "description": [
            {
               "line": "Overwrites the allocation rule of the parallel environment for this scope."
            }
         ],
         "type": "lStringT",
         "flags": [
            {
               "name": "SPOOL"
            }
         ]
      },
      {
         "name": "ignore_slave_requests_on_master_host",
         "summary": "Ignore Slave Requests on Master Host",
         "description": [
            {
               "line": "Overwrites the ignore_slave_requests_on_master_host option of the parallel environment for this scope."
            }
         ],
         "type": "lBoolT",
         "flags": [
            {
               "name": "SPOOL"
            }
         ]
      }
   ]
}

=== snowfrs/clusterscheduler/source/libs/sgeobj/json/NSV.json
{
   "className": "NamedStringVector",
   "summary": "Named String Vector",
   "description": [
      {
         "line": "Used in the DRMAA library to implement vector job template attributes."
      }
   ],
   "cullPrefix": "NSV",
   "attributes": [
      {
         "name": "name",
         "summary": "Name",
         "description": [
            {
               "line": "Name of the string vector."
            }
         ],
         "type": "lStringT",
         "flags": []
      },
      {
         "name": "strings",
         "summary": "Strings",
         "description": [
            {
               "line": "Strings of this string vector."
            }
         ],
         "type": "lListT",
         "subClassName": "ST",
         "subCullPrefix": "ST",
         "flags": []
      }
   ]
}

=== snowfrs/clusterscheduler/source/libs/sgeobj/json/CF.json
{
   "className": "ConfigurationElement",
   "summary": "Configuration Element",
   "description": [
      {
         "line": "A configuration element contains one line of a configuration, see qconf -sconf, e.g."
      },
      {
         "line": "- execd_spool_dir"
      },
      {
         "line": "- mailer"
      },
      {
         "line": "- xterm"
      },
      {
         "line": "- load_sensor"
      },
      {
         "line": "- ..."
      }
   ],
   "cullPrefix": "CF",
   "attributes": [
      {
         "name": "name",
         "summary": "Configuration Name",
         "description": [
            {
               "line": "Name of the configuration element (the left column of qconf -sconf)."
            }
         ],
         "type": "lStringT",
         "flags": [
            {
               "name": "PRIMARY_KEY"
            },
            {
               "name": "UNIQUE"
            },
            {
               "name": "HASH"
            },
            {
               "name": "JGDI_CONF"
            },
            {
               "name": "SPOOL_SUBLIST"
            }
         ]
      },
      {
         "name": "value",
         "summary": "Configuration Value",
         "description": [
            {
               "line": "The value of a configuration element (the right column of qconf -sconf)."
            }
         ],
         "type": "lStringT",
         "flags": [
            {
               "name": "JGDI_CONF"
            },
            {
               "name": "SPOOL_SUBLIST"
            }
         ]
      },
      {
         "name": "sublist",
         "summary": "Configuration Sublist",
         "description": [
            {
               "line": "Recursive Sublist of CF_Type. @todo is it still required? It is only used in libs/gdi/sge_qtcsh.cc."
            }
         ],
         "type": "lListT",
         "subClassName": "ANY",
         "subCullPrefix": "ANY",
         "flags": [
            {
               "name": "JGDI_CONF"
            }
         ]
      },
      {
         "name": "local",
         "summary": "Local Configuration",
         "description": [
            {
               "line": "Is it a local configuration (true) or the global configuration (false)."
            }
         ],
         "type": "lUlongT",
         "flags": [
            {
               "name": "JGDI_HIDDEN"
            }
         ]
      }
   ]
}

=== snowfrs/clusterscheduler/source/libs/sgeobj/json/CAL.json
{
   "className": "Calendar",
   "summary": "Calendar",
   "description": [
      {
         "line": "This data structure represents the SGE calendar object."
      }
   ],
   "cullPrefix": "CAL",
   "attributes": [
      {
         "name": "name",
         "summary": "Name",
         "description": [
            {
               "line": "The calendar name."
            },
            {
               "line": "See man page sge_calendar_conf.5 for detailed information about the attributes."
            }
         ],
         "type": "lStringT",
         "flags": [
            {
               "name": "PRIMARY_KEY"
            },
            {
               "name": "UNIQUE"
            },
            {
               "name": "HASH"
            },
            {
               "name": "JGDI_CONF"
            },
            {
               "name": "SPOOL"
            }
         ]
      },
      {
         "name": "year_calendar",
         "summary": "Year Calendar",
         "description": [
            {
               "line": "A year calendar as string, e.g. 12.03.2004=12-11=off."
            }
         ],
         "type": "lStringT",
         "flags": [
            {
               "name": "JGDI_CONF"
            },
            {
               "name": "SPOOL"
            }
         ]
      },
      {
         "name": "week_calendar",
         "summary": "Week Calendar",
         "description": [
            {
               "line": "A week calendar as string, e.g. mon-fri=6-20=suspended."
            }
         ],
         "type": "lStringT",
         "flags": [
            {
               "name": "JGDI_CONF"
            },
            {
               "name": "SPOOL"
            }
         ]
      },
      {
         "name": "parsed_year_calendar",
         "summary": "Parsed Year Calendar",
         "description": [
            {
               "line": "The year calendar parsed to internal data structures."
            }
         ],
         "type": "lListT",
         "subClassName": "CA",
         "subCullPrefix": "CA",
         "flags": [
            {
               "name": "JGDI_HIDDEN"
            }
         ]
      },
      {
         "name": "parsed_week_calendar",
         "summary": "Parsed Week Calendar",
         "description": [
            {
               "line": "The week calendar parsed to internal data structures."
            }
         ],
         "type": "lListT",
         "subClassName": "CA",
         "subCullPrefix": "CA",
         "flags": [
            {
               "name": "JGDI_HIDDEN"
            }
         ]
      },
      {
         "name": "joker",
         "summary": "Joker",
         "description": [
            {
               "line": "Placeholder which can be used for arbitrary data."
            },
            {
               "line": "Its purpose is to be able to add new attributes without changing the spooling format."
            },
            {
               "line": "It is a list of arbitrary type and it is spooled."
            }
         ],
         "type": "lListT",
         "subClassName": "Variable",
         "subCullPrefix": "VA",
         "flags": [
            {"name": "SPOOL"}
         ]
      }
   ]
}

=== snowfrs/clusterscheduler/source/libs/sgeobj/json/SU.json
{
   "className": "SubmitUser",
   "summary": "Submit User",
   "description": [
      {
         "line": "The list of these objects defines which users are allowed to submit jobs into Cluster Scheduler."
      },
      {
         "line": "It is also used to count the number of active jobs of the user."
      }
   ],
   "cullPrefix": "SU",
   "attributes": [
      {
         "name": "name",
         "summary": "Name",
         "description": [
            {
               "line": "User Name"
            }
         ],
         "type": "lStringT",
         "flags": [
            {
               "name": "UNIQUE"
            },
            {
               "name": "HASH"
            }
         ]
      },
      {
         "name": "jobs",
         "summary": "Jobs",
         "description": [
            {
               "line": "Currently active jobs for this user (including jobs in finished state)."
            }
         ],
         "type": "lUlongT",
         "flags": []
      }
   ]
}

=== snowfrs/clusterscheduler/source/libs/sgeobj/json/ABOOL.json
{
   "className": "AttributeBoolean",
   "summary": "Attribute Boolean",
   "description": [
      {
         "line": "Used for boolean attributes in the cluster queues."
      },
      {
         "line": "Used for the queue rerun attribute."
      }
   ],
   "cullPrefix": "ABOOL",
   "attributes": [
      {
         "name": "href",
         "summary": "Host Reference",
         "description": [
            {
               "line": "Name of a host or a host group."
            }
         ],
         "type": "lHostT",
         "flags": [
            {
               "name": "PRIMARY_KEY"
            },
            {
               "name": "UNIQUE"
            },
            {
               "name": "HASH"
            },
            {
               "name": "SPOOL_SUBLIST"
            }
         ]
      },
      {
         "name": "value",
         "summary": "Value",
         "description": [
            {
               "line": "The boolean value."
            }
         ],
         "type": "lBoolT",
         "flags": [
            {
               "name": "SPOOL_SUBLIST"
            }
         ]
      }
   ]
}

=== snowfrs/clusterscheduler/source/libs/sgeobj/json/LS.json
{
   "className": "LoadSensor",
   "summary": "Load Sensor",
   "description": [
      {
         "line": "The attributes of this element show the state of a load sensor."
      },
      {
         "line": "A list of these elements is used in the execd."
      }
   ],
   "cullPrefix": "LS",
   "attributes": [
      {
         "name": "name",
         "summary": "Name",
         "description": [
            {
               "line": "Name of this load sensor, no hashing, we only have few loadsensors/host."
            },
            {
               "line": "Currently used names:"
            },
            {
               "line": "  - extern"
            },
            {
               "line": "  - IDLE_LOADSENSOR_NAME = qidle"
            },
            {
               "line": "  - GNU_LOADSENSOR_NAME = qloadsensor"
            },
            {
               "line": "@todo what's the purpose of the name?"
            }
         ],
         "type": "lStringT",
         "flags": []
      },
      {
         "name": "command",
         "summary": "Command",
         "description": [
            {
               "line": "Absolute path of the load sensor script / binary."
            }
         ],
         "type": "lStringT",
         "flags": []
      },
      {
         "name": "pid",
         "summary": "Pid",
         "description": [
            {
               "line": "Pid of the load sensor process."
            }
         ],
         "type": "lStringT",
         "flags": []
      },
      {
         "name": "in",
         "summary": "Stdin File Handle",
         "description": [
            {
               "line": "stdin filehandle to the loadsensor process (type FILE *)"
            }
         ],
         "type": "lRefT",
         "subClassName": "ANY",
         "subCullPrefix": "ANY",
         "flags": []
      },
      {
         "name": "out",
         "summary": "Stdout File Handle",
         "description": [
            {
               "line": "stdout filehandle of the loadsensor process (type FILE *)"
            }
         ],
         "type": "lRefT",
         "subClassName": "ANY",
         "subCullPrefix": "ANY",
         "flags": []
      },
      {
         "name": "err",
         "summary": "Stderr File Handle",
         "description": [
            {
               "line": "stderr filehandle of the loadsensor process (type FILE *)"
            }
         ],
         "type": "lRefT",
         "subClassName": "ANY",
         "subCullPrefix": "ANY",
         "flags": []
      },
      {
         "name": "has_to_restart",
         "summary": "Has to restart",
         "description": [
            {
               "line": "Do we have to restart the load sensor script?"
            }
         ],
         "type": "lBoolT",
         "flags": []
      },
      {
         "name": "tag",
         "summary": "Tag",
         "description": [
            {
               "line": "Tag for internal use (@todo 1 means it is running, 0 it isn't running? Verify.)"
            }
         ],
         "type": "lUlongT",
         "flags": []
      },
      {
         "name": "incomplete",
         "summary": "Incomplete Values",
         "description": [
            {
               "line": "Current values we got from the load sensor script."
            }
         ],
         "type": "lListT",
         "subClassName": "LR",
         "subCullPrefix": "LR",
         "flags": []
      },
      {
         "name": "complete",
         "summary": "Complete Values",
         "description": [
            {
               "line": "Last complete set of the load sensor's values."
            }
         ],
         "type": "lListT",
         "subClassName": "LR",
         "subCullPrefix": "LR",
         "flags": []
      },
      {
         "name": "last_mod",
         "summary": "Last Modification Time",
         "description": [
            {
               "line": "Last modification time of the load sensor script."
            },
            {
               "line": "If the script is modified, then the load sensor will be re-started."
            }
         ],
         "type": "lUlongT",
         "flags": []
      }
   ]
}

=== snowfrs/clusterscheduler/source/libs/sgeobj/json/SO.json
{
   "className": "SubordinateQueue",
   "summary": "SubordinateQueue",
   "description": [
      {
         "line": "Subordinate (queue instances) are defined in a sub list of a queue instance."
      },
      {
         "line": "We want to use the configuration parameter subordinate_list"
      },
      {
         "line": "for both the classic queue instance-wise suspend on subordinate"
      },
      {
         "line": "and the slot-wise suspend on subordinate."
      },
      {
         "line": "The fields SO_name and SO_threshold are used by the queue instance-wise"
      },
      {
         "line": "suspend on subordinate, SO_name, SO_slots_sum, SO_seq_no and SO_action"
      },
      {
         "line": "are used by the slot-wise suspend on subordinate."
      },
      {
         "line": "If SO_slots_sum is 0, it's queue instance-wise, otherwise slot-wise"
      },
      {
         "line": "suspend on subordinate that is configured."
      }
   ],
   "cullPrefix": "SO",
   "attributes": [
      {
         "name": "name",
         "summary": "Subordinate Queue Name",
         "description": [
            {
               "line": "Name of the subordinate queue."
            }
         ],
         "type": "lStringT",
         "flags": [
            {
               "name": "PRIMARY_KEY"
            },
            {
               "name": "SPOOL_SUBLIST"
            }
         ]
      },
      {
         "name": "threshold",
         "summary": "Threshold",
         "description": [
            {
               "line": "The threshold (slots) defines when the subordination action (suspend) will be triggered."
            }
         ],
         "type": "lUlongT",
         "flags": [
            {
               "name": "SPOOL_SUBLIST"
            }
         ]
      },
      {
         "name": "slots_sum",
         "summary": "Slots Sum",
         "description": [
            {
               "line": "Used for slot-wise SOS."
            }
         ],
         "type": "lUlongT",
         "flags": [
            {
               "name": "SPOOL_SUBLIST"
            }
         ]
      },
      {
         "name": "seq_no",
         "summary": "Sequence Number",
         "description": [
            {
               "line": "Used for slot-wise SOS."
            }
         ],
         "type": "lUlongT",
         "flags": [
            {
               "name": "SPOOL_SUBLIST"
            }
         ]
      },
      {
         "name": "action",
         "summary": "Action",
         "description": [
            {
               "line": "Subordination action, ussed for slot-wise SOS:"
            },
            {
               "line": "- SO_ACTION_SR: suspend the task with the shortest runtime"
            },
            {
               "line": "- SO_ACTION_LR: suspend the task with the longest runtime"
            }
         ],
         "type": "lUlongT",
         "flags": [
            {
               "name": "SPOOL_SUBLIST"
            }
         ]
      }
   ]
}
